let
    Source = Sql.Database("LAPTOP-ESN8E7MT", "LosAngeles_Crimes", [CreateNavigationProperties=false]),
    Crime_CrimesDim = Source{[Schema="Crime",Item="CrimesDim"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(Crime_CrimesDim,{"Timestamp"}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns","Criminal Threats - No Weapon Displayed","Criminal Threats",Replacer.ReplaceText,{"CrimeName"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Letters, Lewd  -  Telephone Calls, Lewd","Lewd Letters or Calls",Replacer.ReplaceText,{"CrimeName"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Other Miscellaneous Crime","Other Mixed Crimes",Replacer.ReplaceText,{"CrimeName"}),
    #"Added Custom" = Table.AddColumn(#"Replaced Value2", "Crime Cluster", each if Text.Contains([CrimeName], "Homicide") then "Homicide" else if Text.Contains([CrimeName], "Theft Of Identity") then "Identity Theft" else if Text.Contains([CrimeName], "Theft ") then "Theft" else if Text.Contains([CrimeName], "Theft,") then "Theft" else if Text.Contains([CrimeName], "Shoplifting") then "Theft" else if Text.Contains([CrimeName], "Theft-") then "Theft" else if Text.Contains([CrimeName], "Robbery") then "Robbery" else if Text.Contains([CrimeName], "Stolen") then "Stolen" else if Text.Contains([CrimeName], "Burglary") then "Burglary" else if Text.Contains([CrimeName], "Rape") then "Rape" else if Text.Contains([CrimeName], "Vandalism") then "Vandalism" else if Text.Contains([CrimeName], "Bunco") then "Bunco" else if Text.Contains([CrimeName], "Lynching") then "Lynching" else if Text.Contains([CrimeName], "Assault") then "Assault" else if Text.Contains([CrimeName], "Credit Cards, Fraud") then "Fraud" else if Text.Contains([CrimeName], "Till Tap") then "Shoplifting" else if Text.Contains([CrimeName], "Battery") then "Battery" else if Text.Contains([CrimeName], "Kidnapping") then "Kidnapping" else if Text.Contains([CrimeName], "Abortion") then "Abortion" else if Text.Contains([CrimeName], "Violation Of") then "Violation Of Court Order" else if Text.Contains([CrimeName], "Document Worthless") then "Document Worthless" else if Text.Contains([CrimeName], "Dishonest Employee") then "Employee Theft" else if Text.Contains([CrimeName], "Shots Fired") then "Shots Fired" else [CrimeName]),
    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"CrimeName", "Crime Description"}})
in
    #"Renamed Columns"